// DO NOT EDIT THIS MODULE IT IS AUTOGENERATED
import type { DefaultTheme } from 'vitepress'

export const NewsSidebar: DefaultTheme.SidebarItem[] = [
  { text: 'Year 2024', link: '/news/2024.md' },
  { text: 'Year 2023', link: '/news/2023.md' },
  { text: 'Year 2022', link: '/news/2022.md' },
  { text: 'Year 2021', link: '/news/2021.md' },
  { text: 'Year 2020', link: '/news/2020.md' },
  { text: 'Year 2019', link: '/news/2019.md' },
]
