/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimationArrow: typeof import('./.vitepress/theme/components/AnimationArrow.vue')['default']
    ContactInfo: typeof import('./.vitepress/theme/components/ContactInfo.md')['default']
    ContactLinks: typeof import('./.vitepress/theme/components/ContactLinks.md')['default']
    CopyToClipboard: typeof import('./.vitepress/theme/components/CopyToClipboard.vue')['default']
    DelayDemoWrapper: typeof import('./.vitepress/theme/components/DelayDemoWrapper.vue')['default']
    GettingStartedFreedom: typeof import('./.vitepress/theme/components/GettingStartedFreedom.md')['default']
    GettingStartedHero: typeof import('./.vitepress/theme/components/GettingStartedHero.md')['default']
    GettingStartedIconSets: typeof import('./.vitepress/theme/components/GettingStartedIconSets.md')['default']
    GettingStartedIntro: typeof import('./.vitepress/theme/components/GettingStartedIntro.md')['default']
    GettingStartedLicense: typeof import('./.vitepress/theme/components/GettingStartedLicense.md')['default']
    GettingStartedSponsor: typeof import('./.vitepress/theme/components/GettingStartedSponsor.md')['default']
    HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
    HomePageButton: typeof import('./.vitepress/theme/components/HomePageButton.vue')['default']
    IconLoadingProcess: typeof import('./.vitepress/theme/components/IconLoadingProcess.vue')['default']
    LatestNews: typeof import('./.vitepress/theme/components/LatestNews.md')['default']
    LongArrow: typeof import('./.vitepress/theme/components/LongArrow.vue')['default']
    NamespacesAnimation: typeof import('./.vitepress/theme/components/NamespacesAnimation.vue')['default']
    NamespacesName: typeof import('./.vitepress/theme/components/NamespacesName.vue')['default']
    VPCarbonAds: typeof import('./.vitepress/theme/components/VPCarbonAds.vue')['default']
  }
}
